packages:
  - "apps/*"
  - "packages/*"

# Catalog for managing shared dependencies
catalog:
  # React ecosystem
  react: ^18.3.1
  react-dom: ^18.3.1

  # TypeScript
  typescript: ^5.4.5

  # Vite
  vite: ^5.2.0

  # Testing
  vitest: ^1.5.0
  "@testing-library/react": ^15.0.0
  "@testing-library/jest-dom": ^6.4.2

  # ESLint & Prettier
  eslint: ^8.57.0
  prettier: ^3.2.5

  # UI Libraries
  "@radix-ui/react-dialog": ^1.0.5
  "@radix-ui/react-dropdown-menu": ^2.0.6
  "@radix-ui/react-select": ^2.0.0
  tailwindcss: ^3.4.3

  # Utilities
  zod: ^3.23.0
  date-fns: ^3.6.0
